### PR TITLE
Fix off by one error

### PR DESCRIPTION
**Pull request by axelson**
Currently the code is checking `x == size`/`y == size` which means that x/y can grow to 5 when 4 should be the max (given that the board is zero indexed).

With this fix this file `input.txt`:
```
PLACE 1,6,WEST
MOVE
PLACE 3,3,EAST
MOVE
MOVE
RIGHT
MOVE
REPORT
```

Results in correct output:
```
$ _build/prod/rel/bakeware/toy_robot run input.txt
4,2,SOUTH
Result: 4,2,SOUTH
```

### CODE REVIEW

**Comment by christhekeele** [comment]
Good catch! I think I just misunderstood the initial requirements.

I also realize now looking at the OG project requirements:

> The toy robot must not fall off the table during movement. ***This also includes the initial placement of the toy robot. ***

Another issue your example demonstrates!

**Comment by christhekeele** [comment]
Whoops, re-committed the bug in the GH merge conflict resolver UI. Releasing fix shortly

**Comment by christhekeele** [comment]
Fixed, and tests for both issues added to challenge seed project. Thanks!

**Comment by axelson** [comment]
You're welcome!

**Pull request merged**
